[project]
name = "amazon-s3-object-copier"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "boto3>=1.37.37",
]

[tool.black]
skip-string-normalization = true

[tool.isort]
profile = "black"
